title: ELIXIR Data Steward Handbook
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: ""
# Metadata description of the website

theme: elixir-toolkit-theme

topnav_title: Data Steward Handbook

theme_variables:
  topnav:
    brand_logo: assets/img/main_logo.svg

sass:
  style: compressed
  sourcemap: always
  silence_deprecations: # TODO: Fix https://sass-lang.com/documentation/js-api/interfaces/deprecations/
    - import
    - global-builtin
    - color-functions
    - mixed-decls

gtag: 
# Google analytics tag

# dsw_deep_link_prefix: https://researchers.ds-wizard.org/knowledge-models/dsw:root:latest/preview?questionUuid=
# prefix for DSW deep links to a certain question


exclude:
  - README.md
  - Dockerfile
  - vendor
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      search_exclude: false
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/case-studies"
    values:
      sidebar: case-studies
      type: case-studies
  -
    scope:
      path: "pages/case-studies/uk"
    values:
      type: uk
  -
    scope:
      path: "pages/case-studies/nl"
    values:
      type: nl
  -
    scope:
      path: "pages/guidelines"
    values:
      type: guidelines
      sidebar: guidelines
  -
    scope:
      path: "pages/guidelines/g-support"
    values:
     type: guidelines-support
  -
    scope:
      path: "pages/guidelines/rdm-strategy"
    values:
     type: rdm-strategy
  -
    scope:
      path: "pages/maturity-model"
    values:
      sidebar: maturity-model
      type: maturity-model
  -
    scope:
      path: "pages/maturity-model/strategy"
    values:
      type: mm-strategy
  -
    scope:
      path: "pages/maturity-model/legal"
    values:
      type: mm-legal
  -
    scope:
      path: "pages/maturity-model/data"
    values:
      type: mm-data
  -
    scope:
      path: "pages/maturity-model/support"
    values:
      type: mm-support

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick
